### ISSUE TITLE
Compilation of pybuild/PyKF5/KI18n/unifiedKI18n.cpp fails

### ISSUE THREAD

**Issue by JensDA** [chaotic-aur/pkgbuild-ki18n-git#1]
```
==> Making package: ki18n-git 5.83.0_r464.ga07971a-1 (Sun Jul  4 21:48:24 2021)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Updating ki18n git repo...
Fetching origin
==> Validating source files with sha256sums...
    ki18n ... Skipped
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Creating working copy of ki18n git repo...
Cloning into 'ki18n'...
done.
==> Starting pkgver()...
==> Updated version: ki18n-git 5.84.0_r469.gd181a83-1
==> Sources are ready.
==> Making package: ki18n-git 5.84.0_r469.gd181a83-1 (Sun Jul  4 21:48:25 2021)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Starting pkgver()...
==> Removing existing $pkgdir/ directory...
==> Starting build()...
-- The C compiler identification is GNU 11.1.0
-- The CXX compiler identification is GNU 11.1.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- 

-- Installing in the same prefix as Qt, adopting their path scheme.
-- Setting build type to 'Debug' as none was specified.
-- Looking for __GLIBC__
-- Looking for __GLIBC__ - found
-- Performing Test _OFFT_IS_64BIT
-- Performing Test _OFFT_IS_64BIT - Success
-- Performing Test HAVE_DATE_TIME
-- Performing Test HAVE_DATE_TIME - Success
-- Looking for dngettext
-- Looking for dngettext - found
-- libintl is part of libc, no extra library is required.
-- Found LibIntl: /usr/include  
-- Performing Test HAVE_NL_MSG_CAT_CNTR
-- Performing Test HAVE_NL_MSG_CAT_CNTR - Success
-- Found PythonInterp: /usr/bin/python (found version "3.9.6") 
-- Found Gettext: /usr/bin/msgmerge (found version "0.21") 
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
-- Installing in the same prefix as Python3, adopting their path scheme.
-- Installing in the same prefix as Python2, adopting their path scheme.
-- Found /usr/lib/libclang.so
-- Testing if /usr/bin/python2 can be used to run sip_generator
-- Self-check passed, Using /usr/bin/python2 to generate bindings
-- Found dependencies for python3, generating bindings
-- Python3 install dir: /usr/lib/python3.9/site-packages
-- Found dependencies for python2, generating bindings
-- Python2 install dir: /usr/lib/python2.7/site-packages
-- Found Doxygen: /usr/bin/doxygen (found suitable version "1.9.1", minimum required is "1.8.13") found components: doxygen dot 
-- Found QHelpGenerator executable: /usr/bin/qhelpgenerator
-- The following features have been enabled:

 * QCH, API documentation in QCH format (for e.g. Qt Assistant, Qt Creator & KDevelop)

-- The following OPTIONAL packages have been found:

 * PythonModuleGeneration

-- The following REQUIRED packages have been found:

 * ECM (required version >= 5.84.0), Extra CMake Modules., <https://commits.kde.org/extra-cmake-modules>
 * Qt5 (required version >= 5.15.0)
 * Qt5Network (required version >= 5.15.2)
 * Qt5Qml (required version >= 5.15.0)
 * LibIntl, <http://gnuwin32.sourceforge.net/packages/libintl.htm>
   Needed for building KI18n unless glibc is the system libc implementation
 * PythonInterp
 * Gettext
 * Doxygen (required version >= 1.8.13)
   Needed for API dox QCH file generation
 * QHelpGenerator, Part of Qt5 tools
   Needed for API dox QCH file generation
 * Qt5Core

-- Configuring done
-- Generating done
-- Build files have been written to: /home/jens/.cache/yay/ki18n-git/src/build
[  0%] Built target Qt5Core_QCH
[  3%] Automatic MOC for target ktranscript
[  6%] Generating sip/PyKF5/KI18n/klocalizedcontext.sip
[ 10%] Generating sip/PyKF5/KI18n/klocalizedtranslator.sip
[ 13%] Generating sip/PyKF5/KI18n/klocalizedstring.sip
[ 16%] Generating sip/PyKF5/KI18n/kuitsetup.sip
[ 20%] Generating sip/PyKF5/KI18n/kuitmarkup.sip
[ 23%] Automatic MOC for target KF5I18n
[ 26%] Generating src/KF5I18n.qch, src/KF5I18n.tags
[ 26%] Built target KF5I18n_autogen
[ 26%] Built target ktranscript_autogen
[ 30%] Building CXX object src/CMakeFiles/KF5I18n.dir/kcatalog.cpp.o
[ 33%] Building CXX object src/CMakeFiles/KF5I18n.dir/kuitmarkup.cpp.o
[ 36%] Building CXX object src/CMakeFiles/KF5I18n.dir/KF5I18n_autogen/mocs_compilation.cpp.o
[ 40%] Building CXX object src/CMakeFiles/KF5I18n.dir/klocalizedcontext.cpp.o
[ 43%] Building CXX object src/CMakeFiles/KF5I18n.dir/klocalizedstring.cpp.o
[ 46%] Building CXX object src/CMakeFiles/KF5I18n.dir/klocalizedtranslator.cpp.o
[ 50%] Building CXX object src/CMakeFiles/KF5I18n.dir/main.cpp.o
[ 53%] Building CXX object src/CMakeFiles/KF5I18n.dir/ki18n_logging.cpp.o
[ 56%] Building CXX object src/CMakeFiles/KF5I18n.dir/common_helpers.cpp.o
[ 60%] Building CXX object src/CMakeFiles/KF5I18n.dir/ki18n_logging_kuit.cpp.o
[ 63%] Building CXX object src/CMakeFiles/ktranscript.dir/ktranscript.cpp.o
[ 66%] Building CXX object src/CMakeFiles/ktranscript.dir/ktranscript_autogen/mocs_compilation.cpp.o
[ 70%] Building CXX object src/CMakeFiles/ktranscript.dir/common_helpers.cpp.o
Building up file structure...
Insert custom filters...
Insert help data for filter section (1 of 1)...
Insert files...
Insert contents...
Insert indices...
Documentation successfully generated.
[ 70%] Built target KF5I18n_QCH
[ 70%] Built target generate_KI18n_sip_files
[ 73%] Generating pybuild/PyKF5/KI18n/unifiedKI18n.cpp
Traceback (most recent call last):
  File "/usr/share/ECM/find-modules/run-sip.py", line 10, in <module>
    from PyQt5.Qt import PYQT_CONFIGURATION
ImportError: No module named PyQt5.Qt
make[2]: *** [src/CMakeFiles/sip_generated_KI18n_files.dir/build.make:77: src/pybuild/PyKF5/KI18n/unifiedKI18n.cpp] Error 1
make[1]: *** [CMakeFiles/Makefile2:478: src/CMakeFiles/sip_generated_KI18n_files.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 76%] Linking CXX shared library ../bin/libKF5I18n.so
[ 80%] Linking CXX shared module ../bin/ktranscript.so
[ 80%] Built target ktranscript
[ 80%] Built target KF5I18n
make: *** [Makefile:136: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
error making: ki18n-git
```

**Comment by JensDA** [comment]
```
Python 3.9.6 (default, Jun 30 2021, 10:22:16) 
[GCC 11.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from PyQt5.Qt import PYQT_CONFIGURATION
>>> PYQT_CONFIGURATION
{'sip_flags': '-n PyQt5.sip -t Qt_5_15_0 -t WS_X11'}
```

**Comment by IslandC0der** [comment]
Hi, do you have any other python versions installed?

**Comment by JensDA** [comment]
Python 2.7 is installed as `/usr/bin/python2`

**Comment by IslandC0der** [comment]
Uninstalling it "fixes" the problem, right?

**Comment by JensDA** [comment]
Yes, I can confirm that. Unfortunately, I need python2 for DisplayCal.

**Comment by IslandC0der** [comment]
[I think I have finally fixed this!](https://github.com/chaotic-aur/pkgbuild-extra-cmake-modules-git/blob/master/Py2-no-sip.patch)
Could you try compiling `extra-cmake-modules-git` with that patch (you can just `git clone https://github.com/chaotic-aur/pkgbuild-extra-cmake-modules-git`, and then build and install it), and confirm that this issue goes away?

**Comment by JensDA** [comment]
Yes, it is working now. Thanks.

**Comment by IslandC0der** [comment]
Awesome!! Can you still reproduce #2, after recompiling those packages with your new `extra-cmake-modules-git` version?

**Comment by yaomtc** [comment]
I got this similar error while building:

    ```[ 63%] Generating pybuild/PyKF5/KI18n/unifiedKI18n.cpp
    Traceback (most recent call last):
      File "/usr/share/ECM/find-modules/run-sip.py", line 10, in <module>
        from PyQt5.Qt import PYQT_CONFIGURATION
    ImportError: No module named PyQt5.Qt
    make[2]: *** [src/CMakeFiles/sip_generated_KI18n_files.dir/build.make:77: src/pybuild/PyKF5/KI18n/unifiedKI18n.cpp] Error 1
    make[1]: *** [CMakeFiles/Makefile2:301: src/CMakeFiles/sip_generated_KI18n_files.dir/all] Error 2
    make: *** [Makefile:136: all] Error 2

`python-pyqt5` is installed.

**Comment by PedroHLC** [comment]
@yaomtc please, open a new issue, so GitHub notifies only the right people.

**Comment by IslandC0der** [comment]
@yaomtc Have you tried my fix (compiling and installing `extra-cmake-modules-git` with [this patch](https://github.com/chaotic-aur/pkgbuild-extra-cmake-modules-git/blob/master/Py2-no-sip.patch))?
